{% set version = '1.2.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-progress
  version: {{ version|replace("-", "_") }}

source:
  fn: progress_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/progress_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/progress/progress_{{ version }}.tar.gz
  sha256: 5bb9044d1376cf45e8231c94707ccb7f50996f37c52e40771e1f0cde16a81ce6

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-r6
    - r-crayon
    - r-hms
    - r-prettyunits
  run:
    - r-base
    - r-r6
    - r-crayon
    - r-hms
    - r-prettyunits

test:
  commands:
    - $R -e "library('progress')"           # [not win]
    - "\"%R%\" -e \"library('progress')\""  # [win]

about:
  home: https://github.com/r-lib/progress#readme
  license: MIT
  summary: Configurable Progress bars, they may include percentage, elapsed time, and/or the
    estimated completion time. They work in terminals, in 'Emacs' 'ESS', 'RStudio',
    'Windows' 'Rgui' and the 'macOS' 'R.app'. The package also provides a 'C++' 'API',
    that works with or without 'Rcpp'.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
